# Generated by Django 4.1.3 on 2022-11-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog1App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movibilidad',
            name='Musculo_Implicado',
            field=models.CharField(max_length=40),
        ),
    ]
