# Generated by Django 4.1.3 on 2022-11-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog1App', '0002_alter_movibilidad_musculo_implicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antistress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ejercicio', models.CharField(max_length=40)),
                ('Descanso', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Musculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ejercicio', models.CharField(max_length=40)),
                ('Musculo_Implicado', models.CharField(max_length=40)),
                ('Carga', models.IntegerField(max_length=40)),
                ('Descanso', models.CharField(max_length=40)),
            ],
        ),
    ]
