# Generated by Django 4.1.3 on 2022-11-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog1App', '0003_antistress_musculacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='musculacion',
            name='Link_Video',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='musculacion',
            name='Nivel',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='musculacion',
            name='Carga',
            field=models.CharField(max_length=40),
        ),
    ]
