# Generated by Django 4.1.3 on 2022-11-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog1App', '0004_musculacion_link_video_musculacion_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antistress',
            name='Link_Musica',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='antistress',
            name='Link_Video',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='antistress',
            name='Terreno_Recomendado',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
