# Generated by Django 4.1.3 on 2022-12-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog1App', '0005_antistress_link_musica_antistress_link_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musculacion',
            name='Series',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
